-- ============================================================
-- URBANMART POS
-- SQL Business Questions
-- File: 02_Business_Questions.sql
-- ============================================================

SET search_path TO urbanmart;


-- ============================================================
-- SECTION 1 — SALES PERFORMANCE
-- ============================================================

-- Q01
-- What is the total revenue generated by UrbanMart?

-- Q02
-- How many transactions were completed?

-- Q03
-- What is the average transaction value?

-- Q04
-- What is the total discount given to customers?

-- Q05
-- What is the total tax collected?

-- Q06
-- How does revenue vary by transaction date?

-- Q07
-- Which month generated the highest revenue?

-- Q08
-- Which day generated the highest revenue?

-- Q09
-- How many transactions were completed by transaction status?

-- Q10
-- What percentage of transactions were completed successfully?


-- ============================================================
-- SECTION 2 — STORE PERFORMANCE
-- ============================================================

-- Q11
-- Which store generated the highest revenue?

-- Q12
-- Which store generated the lowest revenue?

-- Q13
-- Which stores have the highest transaction count?

-- Q14
-- What is the average transaction value by store?

-- Q15
-- Which stores contribute the largest share of total revenue?

-- Q16
-- Which stores have declining sales performance?

-- Q17
-- Which stores have the highest number of transactions?

-- Q18
-- How does store performance vary by region?

-- Q19
-- How does performance vary by store type?

-- Q20
-- Which stores require management attention based on low revenue?


-- ============================================================
-- SECTION 3 — PRODUCT PERFORMANCE
-- ============================================================

-- Q21
-- Which products generate the highest revenue?

-- Q22
-- Which products have the highest sales quantity?

-- Q23
-- Which products have the lowest sales quantity?

-- Q24
-- Which products contribute the most to total revenue?

-- Q25
-- Which product categories generate the highest revenue?

-- Q26
-- Which product categories sell the highest quantity?

-- Q27
-- Which products have low sales but high inventory?

-- Q28
-- Which products generate the highest average revenue per transaction?

-- Q29
-- Which brands generate the highest revenue?

-- Q30
-- Which products should be reviewed for weak sales performance?


-- ============================================================
-- SECTION 4 — CUSTOMER ANALYSIS
-- ============================================================

-- Q31
-- How many customers have made purchases?

-- Q32
-- Which customer segments generate the highest revenue?

-- Q33
-- Which customer segments have the highest transaction count?

-- Q34
-- What is the average transaction value by customer segment?

-- Q35
-- Which customers have the highest purchase value?

-- Q36
-- Which customers have the highest number of transactions?

-- Q37
-- How much revenue is generated by loyalty customers?

-- Q38
-- How many customers are currently active?

-- Q39
-- What percentage of transactions are associated with a customer?

-- Q40
-- Which customer segments may require targeted marketing?


-- ============================================================
-- SECTION 5 — LOYALTY ANALYSIS
-- ============================================================

-- Q41
-- How many loyalty transactions occurred?

-- Q42
-- How many loyalty points were earned?

-- Q43
-- How many loyalty points were redeemed?

-- Q44
-- How many loyalty points were reversed?

-- Q45
-- Which customers earned the most loyalty points?

-- Q46
-- Which customers redeemed the most loyalty points?

-- Q47
-- What is the relationship between loyalty activity and purchase activity?

-- Q48
-- Which customers have loyalty activity but low purchase frequency?

-- Q49
-- Which customers have high purchase activity but low loyalty activity?

-- Q50
-- What percentage of customers participate in loyalty activity?


-- ============================================================
-- SECTION 6 — INVENTORY ANALYSIS
-- ============================================================

-- Q51
-- How many products are currently in stock?

-- Q52
-- How many products are low in stock?

-- Q53
-- How many products are out of stock?

-- Q54
-- Which stores have the highest number of low-stock products?

-- Q55
-- Which products are below their reorder level?

-- Q56
-- Which products are completely out of stock?

-- Q57
-- Which products have the highest available inventory?

-- Q58
-- Which stores have inventory concentration?

-- Q59
-- Which products have high inventory but low sales?

-- Q60
-- Which products may require replenishment?


-- ============================================================
-- SECTION 7 — RETURN ANALYSIS
-- ============================================================

-- Q61
-- What is the total number of returned units?

-- Q62
-- What is the total refund amount?

-- Q63
-- Which products have the highest return quantity?

-- Q64
-- Which products have the highest return rate?

-- Q65
-- Which stores have the highest return quantity?

-- Q66
-- Which stores have the highest return rate?

-- Q67
-- What are the most common return reasons?

-- Q68
-- Which products generate both high sales and high returns?

-- Q69
-- Which products have low sales but unusually high returns?

-- Q70
-- What percentage of sold units are returned?


-- ============================================================
-- SECTION 8 — PAYMENT ANALYSIS
-- ============================================================

-- Q71
-- What payment methods are used by customers?

-- Q72
-- What is the total payment amount by payment method?

-- Q73
-- Which payment method has the highest transaction value?

-- Q74
-- Which payment method has the highest transaction count?

-- Q75
-- Are there transactions without payment records?

-- Q76
-- Are there transactions where payment totals do not match
-- the transaction total?

-- Q77
-- How many payment transactions failed?

-- Q78
-- Which stores have the highest payment exceptions?

-- Q79
-- What percentage of payments are successful?

-- Q80
-- Which payment methods require further investigation?


-- ============================================================
-- SECTION 9 — RECONCILIATION ANALYSIS
-- ============================================================

-- Q81
-- What is the total reconciliation variance?

-- Q82
-- Which stores have reconciliation variances?

-- Q83
-- Which stores have the highest reconciliation variance?

-- Q84
-- Which reconciliation dates contain exceptions?

-- Q85
-- How many reconciliation records are currently unresolved?

-- Q86
-- Which stores have repeated reconciliation issues?

-- Q87
-- What is the average reconciliation variance by store?

-- Q88
-- Which stores require finance investigation?

-- Q89
-- What are the most common reconciliation exception reasons?

-- Q90
-- What percentage of reconciliation records are successfully resolved?


-- ============================================================
-- SECTION 10 — CHANNEL ANALYSIS
-- ============================================================

-- Q91
-- What transaction channels are being used?

-- Q92
-- Which channel generates the highest revenue?

-- Q93
-- Which channel has the highest transaction count?

-- Q94
-- What is the average transaction value by channel?

-- Q95
-- What percentage of total revenue comes from each channel?

-- Q96
-- How does Store performance compare with Web?

-- Q97
-- How does Mobile performance compare with Store?

-- Q98
-- Which channel has the highest customer activity?

-- Q99
-- Which channel has the highest return activity?

-- Q100
-- Which channel should management prioritize for growth?


-- ============================================================
-- SECTION 11 — CROSS-FUNCTIONAL ANALYSIS
-- ============================================================

-- Q101
-- Which stores have high revenue but high return rates?

-- Q102
-- Which stores have high revenue but low inventory availability?

-- Q103
-- Which products have high sales and low inventory?

-- Q104
-- Which products have low sales and high inventory?

-- Q105
-- Which products have high sales and high return rates?

-- Q106
-- Which customer segments generate high revenue but low loyalty activity?

-- Q107
-- Which stores have high sales but payment reconciliation issues?

-- Q108
-- Which channels have high revenue but high return rates?

-- Q109
-- Which stores have strong sales and healthy inventory?

-- Q110
-- Which business areas require the highest management attention?


-- ============================================================
-- SECTION 12 — MANAGEMENT KPI QUESTIONS
-- ============================================================

-- Q111
-- What is UrbanMart's total revenue?

-- Q112
-- What is the total transaction count?

-- Q113
-- What is the average transaction value?

-- Q114
-- What is the total number of units sold?

-- Q115
-- What is the total return quantity?

-- Q116
-- What is the overall return rate?

-- Q117
-- What is the total refund amount?

-- Q118
-- How many products are low in stock?

-- Q119
-- What is the total reconciliation variance?

-- Q120
-- What is the overall payment success rate?


-- ============================================================
-- SECTION 13 — PRIORITY BUSINESS QUESTIONS
-- ============================================================

/*
The following questions are the highest-value questions
selected for the main portfolio analysis.
*/


-- PRIORITY 01
-- Which stores generate the highest revenue?


-- PRIORITY 02
-- Which products generate the highest revenue?


-- PRIORITY 03
-- Which product categories perform best?


-- PRIORITY 04
-- What is the average transaction value by store?


-- PRIORITY 05
-- Which products are low in stock?


-- PRIORITY 06
-- Which stores have the highest number of low-stock products?


-- PRIORITY 07
-- Which products have the highest return rate?


-- PRIORITY 08
-- Which stores have the highest return rate?


-- PRIORITY 09
-- Which payment transactions have reconciliation issues?


-- PRIORITY 10
-- Which stores have reconciliation variances?


-- PRIORITY 11
-- Which customer segments generate the highest revenue?


-- PRIORITY 12
-- Which transaction channel generates the highest revenue?


-- PRIORITY 13
-- Which products have high sales but low inventory?


-- PRIORITY 14
-- Which products have low sales but high inventory?


-- PRIORITY 15
-- Which business areas require management attention?


-- ============================================================
-- SECTION 14 — QUESTION-TO-TABLE MAPPING
-- ============================================================

/*
Business Question → Main Tables

Sales Performance
    → transactions

Store Performance
    → stores + transactions

Product Performance
    → products + transaction_details

Category Performance
    → products + product_categories + transaction_details

Customer Analysis
    → customers + transactions

Loyalty Analysis
    → customers + loyalty_transactions

Inventory Analysis
    → stores + products + inventory

Return Analysis
    → returns + transactions + transaction_details + products

Payment Analysis
    → transactions + payments

Reconciliation
    → stores + reconciliation

Channel Analysis
    → transactions

Cross-functional Analysis
    → multiple related tables
*/


-- ============================================================
-- SECTION 15 — QUESTION PRIORITIZATION FRAMEWORK
-- ============================================================

/*
Priority A — Executive / High Business Value

1. Total Revenue
2. Store Revenue
3. Product Revenue
4. Inventory Risk
5. Return Rate
6. Payment Exceptions
7. Reconciliation Variance
8. Channel Performance


Priority B — Operational

1. Transaction Count
2. Average Transaction Value
3. Low Stock Count
4. Return Reasons
5. Payment Method Performance
6. Customer Segment Performance


Priority C — Detailed / Supporting

1. Individual Customer Analysis
2. Individual Product Analysis
3. Loyalty Activity Details
4. Daily / Monthly Trend Analysis
5. Exception-Level Investigation
*/


-- ============================================================
-- SECTION 16 — FINAL BUSINESS ANALYSIS FLOW
-- ============================================================

/*

Business Requirement
        ↓
Business Question
        ↓
Required Data
        ↓
Required Tables
        ↓
SQL Query
        ↓
Result
        ↓
KPI
        ↓
Business Insight
        ↓
Recommendation
        ↓
Power BI Visualization

*/


-- ============================================================
-- END OF FILE
-- ============================================================
